spring:
  application:
    name:Load-testing-with-Gatling

  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-server: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

app:
  kafka:
    topic:
      order-events: order-events